### ISSUE TITLE
Broken miniplayer

### ISSUE THREAD

**Issue by xcasxcursex** [SeinopSys/YTMySubs#8]
If you open a video from your subs page or a playlist or similar, you can click the miniplayer icon, and the video page shrinks and the previous page is shown; the subs page or playlist or whatever....

But if you click a link to youtube, then click the miniplayer icon, there's no 'previous' page, so it uses the youtube home page as the background for the miniplayer. At this point, the plugin takes over, redirects to the subs page, and the video in the miniplayer closes.

Not sure if this is avoidable in practical terms, but reporting nonetheless. Thanks for an awesome addon mate.

**Comment by SeinopSys** [comment]
Due to the mechanism used by the extension to perform the redirect it's not feasible to preserve things like that. It's certainly possible with additional effort, but in the interest of preserving my sanity I'm relying only on the browser APIs which are unlikely to break due to a YouTube update for example. In the scope of this extension, I'm afraid I can't help you with that.

**Comment by xcasxcursex** [comment]
> Due to the mechanism used by the extension to perform the redirect it's not feasible to preserve things like that. It's certainly possible with additional effort, but in the interest of preserving my sanity I'm relying only on the browser APIs which are unlikely to break due to a YouTube update for example. In the scope of this extension, I'm afraid I can't help you with that.

I figured as much, no problem, and thanks again mate.
